/* tslint:disable */
// generated by typescript-json-validator
import { inspect } from "util";
import Ajv from "ajv";
import IMealPlanState from "./types";
export const ajv = new Ajv({
  allErrors: true,
  coerceTypes: false,
  format: "fast",
  nullable: true,
  unicode: true,
  uniqueItems: true,
  useDefaults: true,
});

ajv.addMetaSchema(require("ajv/lib/refs/json-schema-draft-06.json"));

export const IMealPlanStateSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  defaultProperties: [],
  definitions: {
    IMealPlanItem: {
      defaultProperties: [],
      properties: {
        servings: {
          type: "number",
        },
        uuid: {
          type: "string",
        },
      },
      required: ["servings", "uuid"],
      type: "object",
    },
  },
  properties: {
    plan: {
      additionalProperties: {
        items: {
          $ref: "#/definitions/IMealPlanItem",
        },
        type: "array",
      },
      defaultProperties: [],
      type: "object",
    },
    version: {
      type: "string",
    },
  },
  required: ["plan", "version"],
  type: "object",
};
export type ValidateFunction<T> = ((data: unknown) => data is T) &
  Pick<Ajv.ValidateFunction, "errors">;
export const isIMealPlanState = ajv.compile(
  IMealPlanStateSchema
) as ValidateFunction<IMealPlanState>;
export default function validate(value: unknown): IMealPlanState {
  if (isIMealPlanState(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(
        isIMealPlanState.errors!.filter((e: any) => e.keyword !== "if"),
        { dataVar: "IMealPlanState" }
      ) +
        "\n\n" +
        inspect(value)
    );
  }
}
