/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv from 'ajv';
import IUserState from './types.d';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export const IUserStateSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "properties": {
    "version": {
      "type": "string"
    }
  },
  "required": [
    "version"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isIUserState = ajv.compile(IUserStateSchema) as ValidateFunction<IUserState>;
export default function validate(value: unknown): IUserState {
  if (isIUserState(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isIUserState.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'IUserState'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
